// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import HelloController from './hello_controller';
import BudgetController from './budget_controller';
import DisableWalletOrGoal from './disable_wallet_or_goal';
import BottomNavController from './bottom_nav_controller';
import GoalUpdateModalController from './goal_update_modal_controller';

application.register('hello', HelloController);
application.register('budget',BudgetController);
application.register('disable-wallet-goal', DisableWalletOrGoal);
application.register('bottom-nav', BottomNavController);
application.register('goal-update-modal', GoalUpdateModalController);
