// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import DateTimePickerController from './datetimepicker_controller';
import TomSelectBasicController from './tom_select/basic_controller';
import TomSelectRemoteController from './tom_select/remote_controller';
import ModalController from './modal_controller';
application.register('datetimepicker', DateTimePickerController);
application.register('tom-select-basic', TomSelectBasicController);
application.register('tom-select-remote', TomSelectRemoteController);
application.register('modal', ModalController);
